### ISSUE TITLE
answerReview fails due to Retrofit Query location in POST

### ISSUE THREAD

**Issue by AustinSumigray** [esnaultdev/BunPyro#1]
In BunproVesionedApi.kt, the reviewId and correct POST, the POST and suspend lines need to be changed to 
```
    @POST("v3/reviews/edit/{reviewId}")
    suspend fun answerReview(@Path("reviewId") reviewId: Long,
                             @Query("correct") correct: Boolean): Response<Unit>
```
otherwise reviews will fail.

**Comment by esnaultdev** [comment]
Sorry for the delay of my answer, I was busy with something else :bowing_man:

Thank you for the detailed report, it should be fixed by 8ac8dbc31a90888632e840c6f17c90a83ea15cb1.

Note that the `develop` branch of this repo is my work branch, so the reviews are actually WIP.
Thank you for the reports about this feature, but note that it's not officially released yet :wink:
