### ISSUE TITLE
Is “custom-sqlite.aar” open source?

### ISSUE THREAD

**Issue by FangWW** [esnaultdev/BunPyro#10]
I want to use sqlitex to implement a Chinese word tokenizer, but I haven't found a suitable example. I wonder if your "custom SQLite. AAR" is open source?
 Looking forward to your reply, thank you.

**Comment by esnaultdev** [comment]
`custom-sqlite.aar` was generated by using this project: https://github.com/JeremiahStephenson/SQLite_Custom
So it's indeed open source, and you can add custom tokenizers.

I made a couple of adjustments for BunPyro specifically in a fork. You can check the lastest commits here: https://github.com/esnaultdev/SQLite_Custom/commits/bunpyro

**Comment by FangWW** [comment]
Thank you for your reply.
I found some of your git commit info: https://github.com/esnaultdev/BunPyro/commit/e1cbefc5b7f0054435fdf5a0ba49b11eccc45d76

I am also very worried about introducing a custom sqlite, which will make the apk much larger, and cannot ensure its stability on different mobile phones.

I studied ["SQLite_Custom"](https://github.com/JeremiahStephenson/SQLite_Custom) .This is great, but I feel that it has changed a lot of code. I want to find a way to accomplish the function of[ "fts custom tokenizer"](https://www.sqlite.org/fts3.html#creating_and_destroying_fts_tables) with less intrusion code.

Do you have a better suggestion?

**Comment by esnaultdev** [comment]
Thanks, I had forgotten about this commit message.

> I am also very worried about introducing a custom sqlite, which will make the apk much larger, and cannot ensure its stability on different mobile phones.

I haven't experienced any stability issue, and from the crash reports of my users, I don't think that there is any. But if there were any, that would be tricky to diagnose and solve, indeed.
For the apk size, it's true that this isn't optimal. One good thing with the Play Store now enforcing `.aab`s instead of `.apk`s is that users only pay the cost of one ABI. 

> Do you have a better suggestion?

Not really. You can maybe look into [androidx.appsearch](https://developer.android.com/guide/topics/search/appsearch) that was released recently. It aims to provide better search for local data, so it could be a good match for what you need. I have not used it personally, so I'm not sure if it handles custom tokenizers.
One drawback is that this is document based.

**Comment by FangWW** [comment]
Thanks for communicating with you.

I also recently discovered appsearch.

I evaluated several schemes for full text search. Decided to use this repository [requery/sqlite-android](https://github.com/requery/sqlite-android).

It has a convenient interface to register the tokenizer:[SQLiteCustomExtension](https://github.com/requery/sqlite-android/blob/29770360819e9b3671e8ed6b891e5cd514b0b32a/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteCustomExtension.java#L35).
